FROM eclipse-temurin:21-jre
COPY target/*.jar WirSchiffenDas-Starting-Monitoring-Microservice-0.0.1-SNAPSHOT
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/WirSchiffenDas-Starting-Monitoring-Microservice-0.0.1-SNAPSHOT"]
