FROM eclipse-temurin:21-jre
COPY target/*.jar WirSchiffenDas-Engine-Management-Microservice-0.0.1-SNAPSHOT
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "/WirSchiffenDas-Engine-Management-Microservice-0.0.1-SNAPSHOT"]
