version: '3.8'

services:
  kafka-broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  frontend:
    build: WirSchiffenDas-Frontend
    ports:
      - "8080:8080"
    container_name: frontend
    depends_on:
      - kafka-broker
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
  starting-monitoring-module:
    build: WirSchiffenDas-Starting-Monitoring-Module
    container_name: starting-monitoring-module
    depends_on:
      - kafka-broker
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
  mounting-module:
    build: WirSchiffenDas-Mounting-Module
    container_name: mounting-module
    depends_on:
      - kafka-broker
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
  fuel-module:
    build: WirSchiffenDas-Fuel-Module
    container_name: fuel-module
    depends_on:
      - kafka-broker
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
  cooling-module:
    build: WirSchiffenDas-Cooling-Module
    container_name: cooling-module
    depends_on:
      - kafka-broker
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
  engine-mng-module:
    build: WirSchiffenDas-Engine-Management-Module
    container_name: engine-mng-module
    depends_on:
      - kafka-broker
      - starting-monitoring-module
      - mounting-module
      - fuel-module
      - cooling-module
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
